name: dmg_webview
description: "DMG mobile webview shell (1:1 with Next.js mobile)"
publish_to: 'none'

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.3.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.4
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.png
  android_12:
    color: "#FFFFFF"
    image: assets/splash.png
  web: false

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

